name: mnist-env
dependencies:
  - python
  - numpy
  - pip:
    - matplotlib
    - tensorflow
    - sklearn
    - pandas
    - seaborn
    - networkx
    - geopandas
    - descartes
    - mapclassify

